### ISSUE TITLE
Adapter cant login to Neato Cloud

### ISSUE THREAD

**Issue by Maveric2005** [Pmant/ioBroker.botvac#18]
Atm the login is not posible.

Like descripted in this iobroker post.

https://forum.iobroker.net/topic/44525/neato-botvac-adapter-1-0-0-0-kein-login-m%C3%B6glich

and in this.

https://forum.iobroker.net/topic/3040/neato-botvac-connected-adapter/151

Do you have a workaround or solution for it?

botvac.0 | 2021-04-24 15:29:17.470 | warn | (950) login failed
-- | -- | -- | --
botvac.0 | 2021-04-24 15:24:16.738 | warn | (950) login failed
botvac.0 | 2021-04-24 15:19:15.667 | warn | (950) login failed

**Comment by Pmant** [comment]
#16
