### ISSUE TITLE
Neato Botvac Connected D3 Staubsauger Roboter

### ISSUE THREAD

**Issue by D4rkF4ce** [Pmant/ioBroker.botvac#3]
Hallo!

Ich bin gerade auf diesen iobroker Adapter gestoßen.
Ich denke das ist das was ich suche!

Funktioniert dieser auch mit dem **Neato Botvac Connected D3 Staubsauger Roboter**?

Hat jemand bereits Erfahrungen gemacht?
Ich wäre für jedes Feedback sehr dankbar bevor ich über 300EUR aus dem Fenster werfe.

Danke euch :)
LG,
Dark!

**Comment by Matten-Matten** [comment]
Mit meinem D3 funktioniert es wunderbar. Ich hab lediglich die Navigation Mode Funktion (extracare) hinzugefügt.

**Comment by D4rkF4ce** [comment]
klappt alles wunderbar! Vielen Dank!
