### ISSUE TITLE
mit Botvac D3 reachable Status probleme

### ISSUE THREAD

**Issue by Matten-Matten** [Pmant/ioBroker.botvac#4]
Moin, 
Ich habe mit Botvac D3 reachable Status probleme. wenn der Botvac nicht erreichbar ist (AUS)
schaltet der `reachable` Status nicht auf "`false`" um.

ich hab darauf hin in der Zeile 659 der Datei main.js das " `, true` " entfernt und jetzt schaltet der `reachable` Status auf "`false`" um.

![einstellungen-07 02 2018_02_24_33](https://user-images.githubusercontent.com/32074970/35893390-26ea2314-0bae-11e8-955a-f6cd75a79b5a.png)

**Comment by Pmant** [comment]
Danke, das ist ein Bug, werde ich demnächst beheben. Hinten müsste übrigens dafür ein "true" hin.

**Comment by Matten-Matten** [comment]
Ok, ich hab das mal mit "true" getestet und der Wert springt dann wieder nicht auf "false" um bei fehlender Komunikation.
 

Mit freundlichen Grüßen
Matthias


 

Gesendet: Mittwoch, 07. Februar 2018 um 12:40 Uhr
Von: Pmant <notifications@github.com>
An: "Pmant/ioBroker.botvac" <ioBroker.botvac@noreply.github.com>
Cc: Matten-Matten <matze-ms@web.de>, Author <author@noreply.github.com>
Betreff: Re: [Pmant/ioBroker.botvac] mit Botvac D3 reachable Status probleme (#4)


Danke, das ist ein Bug, werde ich demnächst beheben. Hinten müsste übrigens dafür ein "true" hin.

**Comment by Matten-Matten** [comment]
![botvac](https://user-images.githubusercontent.com/32074970/35948138-677ecf2a-0c6b-11e8-9b49-993d5f997ba2.png)

**Comment by Pmant** [comment]
> Ok, ich hab das mal mit "true" getestet und der Wert springt dann wieder nicht auf "false" um bei fehlender Komunikation.
 
Also so:
`adapter.setState(robot.name + '.status.reachable', false, true);`
Damit sollte es auf false gesetzt werden mit ack = true, also bestätigt.
