### ISSUE TITLE
meaning of 'state' value

### ISSUE THREAD

**Issue by prankousky** [Pmant/ioBroker.botvac#8]
Hi,

I have been using this adapter for a while and love it. It allows one to control botvac via alexa, mqtt, scripts... it is awesome!

Right now I am trying to integrate the status output in a graphical dashboard... can anybody please tell me what the state values mean? I assume that `1` means `charging at station`, because that's what it shows at the moment (and it is fully charged and at its station).

However, does anybody have a full overview of what other digits there are and what those mean? Thanks in advance for your help 👍

**Comment by bauer1418** [comment]
Hi,

i'm think the state has the following meanings:

0= ready to clean
1=charging
2=cleaning
3=pause

But the state value can be other states for which I don't know the meaning.

So I'm looking for a explaining from the developer too.

Thanks Andreas;)

**Comment by prankousky** [comment]
Thank you @bauer1418 

I'll wait for all those states until I implement them in my logic. The most important values I am looking for are those error message... At the moment I always just get "neato has some problem" (or "Sally hat ein Problem", as this is its name ;) ). It'd be nice to grab those error message, like "Bitte Weg freiräumen", "Bitte Bürste reinigen", etc. to know WHAT the problem ist.

I get errors via telegram message, and don't always feel like checking up on the vacuum, so it'd be nice to know what its actual problem is :)

**Comment by stephan1827** [comment]
Sorry for the german but google translate should work fine
iobroker script for translating states

createState('Neato.BotvacAction', 'Nichts');

var codesToMessage = { '0' : "Keine Aktion", '1' : "Haus-Reinigung", '2' : "Spot-Reinigung", '3' : "Manuelle Reinigung", '4' : "Docking", '5' : "User Menu aktiv", '6' : "Reinigung ausgesetzt", '7' : "Updating", '8' : "Logs kopieren", '9' : "Position ermitteln", '10' : "IEC Test", '12' : "Erstelle Karte",};
on("botvac.0.Robby.status.action"/*action*/, function (obj) { log(obj.state.val);
if (codesToMessage.hasOwnProperty(obj.state.val)) { log('->' + codesToMessage[obj.state.val]);
setState('Neato.BotvacAction', codesToMessage[obj.state.val], true); } 
else { setState('Neato.BotvacAction', obj.state.val); } });

**Comment by stephan1827** [comment]
And the same for the erros

createState('Neato.BotvacError', 'Kein Fehler');

var codesToMessage = { 'ui_alert_invalid': 'Alles in Ordnung', 'ui_error_dust_bin_full': 'Staubbehälter voll', 'ui_error_brush_stuck': 'Bürste verklemmt', 'ui_alert_recovering_location' : 'Ermittle meinen Standort', 'ui_error_picked_up' : 'Wurde angehoben!', 'ui_error_stuck' : 'Ich hänge fest!', 'ui_error_dust_bin_emptied' : 'Staubbehälter wurde geleert!', 'ui_error_dust_bin_missing' : 'Staubbehälter fehlt!', 'ui_error_navigation_falling' : 'Bitte Weg freiräumen!', 'ui_error_navigation_noprogress' : 'Bitte Weg freiräumen!' };

on("botvac.0.Robby.status.error"/*error*/, function (obj) { log(obj.state.val); 
if (codesToMessage.hasOwnProperty(obj.state.val)) { log('->' + codesToMessage[obj.state.val]); 
setState('Neato.BotvacError', codesToMessage[obj.state.val], true); } 
else { setState('Neato.BotvacError', obj.state.val); } });

**Comment by dunbakkie** [comment]
Hi all,
love this adapter!
I am quite new to github...
My neato D7 doesn´t write any errors into iobroker. Any idea?
Do you need any system information?

Also it would be great, if zones could be added. Where can I place this request?

Best regards,
dunbakkie
